#!/bin/bash

UBUNTU="jammy"
UBUNTU_ARCH="amd64"
KERNEL_PACKAGE="linux-image-unsigned-6.2.0-34-generic"

DOMAIN="zhurko.de"

ONHOST="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
. ${ONHOST}/config
baremetal_config

alternate_wipe
alternate_partition
alternate_md
alternate_format
alternate_mount_baremetal

. ${ONHOST}/setup/ubuntu
. ${ONHOST}/setup/ubuntu-kernel

alternate_fstab
alternate_bless
