#!/bin/bash

# install boot loaders and kernel
spawn_chroot "DEBIAN_FRONTEND=noninteractive apt-get -y install extlinux grub-efi-amd64 linux-firmware linux-image-amd64"

#wget https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain/rtl_nic/rtl8125a-3.fw
#mkdir -p /mnt/baremetal/lib/firmware/rtl_nic/
#cp -v rtl8125a-3.fw /mnt/baremetal/lib/firmware/rtl_nic/rtl8125a-3.fw
#spawn_chroot "dpkg -i /root/kernel-5.4.192/*.deb"
